export {default as Actors} from './Actors/Actors.jsx'
export {default as Movies} from './Movies/Movies.jsx'
export {default as Profile} from './Profile/profile.jsx'
export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as MovieInformation} from './MoviesInformation/MoviesInformation.jsx'